import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/druid"),
);
const icons = requireAll(require.context("../../assets/icons/druid"));

export const data: TalentData = {
  Balance: {
    name: "Balance",
    background: backgrounds["balance"],
    icon: icons["spell_nature_starfall"],
    talents: {
      "Starlight Wrath": {
        name: "Starlight Wrath",
        pos: "a1",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the cast time of your Wrath and Starfire spells by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec.`,
      },
      "Improved Moonfire": {
        name: "Improved Moonfire",
        pos: "a2",
        icon: icons["spell_nature_starfall"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the critical strike chance of your Moonfire spell by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Cycle of Life": {
        name: "Cycle of Life",
        pos: "a3",
        icon: icons["cycle_of_life"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Gives you a ${[
          50,
          100,
        ]}% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor. This effect also allows 50% of your Mana Regeneration to continue while casting. Lasts 15 seconds.`,
      },
      "Mighty Roots": {
        name: "Mighty Roots",
        pos: "b1",
        icon: icons["spell_nature_thorns"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Improves the duration and damage of your Entangling roots and Thorns spells by ${[
          40,
          70,
          100,
        ]}%.`,
      },
      "Natural Weapons": {
        name: "Natural Weapons",
        pos: "b2",
        icon: icons["inv_staff_01"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the damage you deal with all attacks and spells by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Unity With Nature": {
        name: "Unity With Nature",
        pos: "b3",
        icon: icons["unity_with_nature"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Reduces the cooldown of your Barkskin by ${[
          1,
          2,
          3,
        ]}min and reduces damage taken from Arcane and Nature effects by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Improved Faerie Fire": {
        name: "Improved Faerie Fire",
        pos: "c1",
        icon: icons["spell_nature_faeriefire"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Icreases the range and armor reduction of your Faerie Fire and Faerie Fire (Feral) spells by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Hurricane": {
        name: "Hurricane",
        pos: "c3",
        icon: icons["spell_nature_cyclone"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Creates a violent storm in the target area causing 27 Nature damage to enemies every 1 sec, slowing their movement speed by 50% and silencing them. Lasts 10 sec.`,
      },
      "Starfall": {
        name: "Starfall",
        pos: "c4",
        icon: icons["spell_arcane_starfire"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Cause your Starfire and Moonfire spells to stun the target for 4 sec if the target is withing 8yds. Can occur once per ${[
          60,
          50,
          40,
          30,
          20,
        ]} sec.`,
      },
      "Omnipresence": {
        name: "Omnipresence",
        pos: "d1",
        icon: icons["spell_nature_naturetouchgrow"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the range of you offensive Balance spells by ${[
          10,
          20,
        ]}% and reduces the chance enemies will resist them by ${[
          2,
          4,
        ]}%.`,
      },
      "Vengeance": {
        name: "Vengenace",
        pos: "d2",
        icon: icons["spell_nature_purge"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Natural Weapons",
        arrows: [{ dir: "down", from: "b2", to: "d2" }],
        description: talentText`Increases the critical strike damage bonus of your offensive spells by ${[
          20,
          40,
          60,
          80,
          100,
        ]}%. and for your feral abilites by ${[
          7,
          14,
          21,
          28,
          35,
        ]}%.`,
      },
      "Power of Nature": {
        name: "Power of Nature",
        pos: "d3",
        icon: icons["power_of_nature"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the duration of your Barkskin, Nature's Grasp, Moonfire, Insect Swarm, Faerie Fire, Rejuvenation, Regrowth, Hibernate, Soothe Animal and Abolish Poison by ${[
          25,
          50,
        ]}%. In addition, increases the number of charges of your Nature's Grasp spell by ${[
          2,
          4,
        ]}.`,
      },
      "Dreamstate": {
        name: "Dreamstate",
        pos: "e1",
        icon: icons["dreamstate"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Regenerates ${[
          1,
          2,
          3,
        ]}% of your total Mana every 10 seconds`,
      },
      "Moonkin Form": {
        name: "Moonkin Form",
        pos: "e2",
        icon: icons["spell_nature_forceofnature"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Transforms the Druid into Moonkin Form, increasing spell damage by up to 20% of your total intellect and armor contribution from items by 360%. The Moonkin can only cast Balance spells while shapeshifted.\n\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.`,
      },
      "Nature's Grace": {
        name: "Nature's Grace",
        pos: "e3",
        icon: icons["spell_nature_naturesblessing"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`All spell criticals grace you with a blessing of nature, reducing the casting time of your next spell by 0.5 sec.`,
      },
      "Moonglow":{
        name: "Moonglow",
        pos: "e4",
        icon: icons["spell_nature_sentinal"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduces the Mana cost of your Moonfire, Starfire, Wrath, Healing Touch, Regrowth and Rejuvenation spells by ${[
          5,
          10,
          15,
        ]}%.`
      },
      "Moonfury": {
        name: "Moonfury",
        pos: "f1",
        icon: icons["moonfury"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage done by your Starfire, Moonfire and Wrath spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%`,
      },
      "Nature Balancer": {
        name: "Nature Balancer",
        pos: "f3",
        icon: icons["nature_balancer"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Nature's Grace",
        arrows: [{dir: "down", from: "e3", to: "f3"}],
        description: talentText`Your Wrath spell have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance of your next Moonfire or Starfire by 30%, and your Moonfire or Starfire spells have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to increase critical strike chance of your next Wrath by 30%`
      },
      "Moonkin Aura": {
        name: "Moonkin Aura",
        pos: "g2",
        icon: icons["spell_nature_forceofnature"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Moonkin Form",
        arrows: [{dir: "down", from: "e2", to: "g2"}],
        description: talentText`While in Moonkin Form, the Moonkin Aura increases spell critical chance of all raid members within 30 yards by 3%.`,
      },
    },
  },
  "Feral Combat": {
    name: "Feral Combat",
    background: backgrounds["feral"],
    icon: icons["ability_racial_bearform"],
    talents: {
      Ferocity: {
        name: "Ferocity",
        pos: "a2",
        icon: icons["ability_hunter_pet_hyena"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the cost of your Maul, Swipe, Claw and Rake abilities by ${[
          1,
          2,
          3,
          4,
          5,
        ]} Rage or Energy.`,
      },
      "Feral Aggression": {
        name: "Feral Aggression",
        pos: "a3",
        icon: icons["ability_druid_demoralizingroar"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the Attack Power reduction of your Demoralizing Roar by ${[
          8,
          16,
          24,
          32,
          40,
        ]}% and the damage caused by your Ferocious Bite by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Feral Instinct": {
        name: "Feral Instinct",
        pos: "b1",
        icon: icons["ability_ambush"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the threat caused in Bear and Dire Bear forms by ${[
          3,
          6,
          9,
          12,
          15,
        ]}% and reduces the chance enemies have to detect you while Prowling.`,
      },
      "Brutal Impact": {
        name: "Brutal Impact",
        pos: "b2",
        icon: icons["ability_druid_bash"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the stun duration of your Bash and Pounce abilities by ${[
          0.5,
          1,
        ]} sec.`,
      },
      "Thick Hide": {
        name: "Thick Hide",
        pos: "b3",
        icon: icons["inv_misc_pelt_bear_03"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your Armor contribution from items by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Feline Swiftness": {
        name: "Feline Swiftness",
        pos: "c1",
        icon: icons["spell_nature_spiritwolf"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your movement speed by ${[
          15,
          30,
        ]}% while outdoors in Cat Form and increases your chance to dodge while in Cat Form by ${[
          2,
          4,
        ]}%.`,
      },
      "Feral Charge": {
        name: "Feral Charge",
        pos: "c2",
        icon: icons["ability_hunter_pet_bear"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Causes you to charge an enemy, immobilizing and interrupting any spell being cast for 4 sec.`,
      },
      "Sharpened Claws": {
        name: "Sharpened Claws",
        pos: "c3",
        icon: icons["inv_misc_monsterclaw_04"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your critical strike chance while in Bear, Dire Bear or Cat Form by ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Improved Shred": {
        name: "Improved Shred",
        pos: "d1",
        icon: icons["spell_shadow_vampiricaura"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Reduces the Energy cost of your Shred ability by ${[
          6,
          12,
        ]}.`,
      },
      "Predatory Strikes": {
        name: "Predatory Strikes",
        pos: "d2",
        icon: icons["ability_hunter_pet_cat"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases your attack power in Cat, Bear and Dire Bear Forms by ${[
          50,
          100,
          150,
        ]}% of your level.`,
      },
      "Blood Frenzy": {
        name: "Blood Frenzy",
        pos: "d3",
        icon: icons["ability_ghoulfrenzy"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Sharpened Claws",
        arrows: [{ dir: "down", from: "c3", to: "d3" }],
        description: talentText`Your critial strikes from Cat Form abilities that add combo points have a ${[
          50,
          100,
        ]}% chance to add an additional combo point.`,
      },
      "Primal Fury": {
        name: "Primal Fury",
        pos: "d4",
        icon: icons["ability_racial_cannibalize"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Sharpened Claws",
        arrows: [
          { dir: "right-down", from: "c3", to: "c4" },
          { dir: "right-down-down", from: "c4", to: "d4" },
        ],
        description: talentText`Gives you ${[
          50,
          100,
        ]} chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form.`,
      },
      "Savage Fury": {
        name: "Savage Fury",
        pos: "e1",
        icon: icons["ability_druid_ravage"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases the damage caused by your Claw, Rake, Maul and Swipe abilities by ${[
          10,
          20,
        ]}%.`,
      },
      "Faerie Fire (Feral)": {
        name: "Faerie Fire (Feral)",
        pos: "e3",
        icon: icons["spell_nature_faeriefire"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Decrease the armor of the target by 175 for 40 sec. While affected, the target cannot stealth or turn invisible.`,
      },
      "Heart of the Wild": {
        name: "Heart of the Wild",
        pos: "f2",
        icon: icons["spell_holy_blessingofagility"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Predatory Strikes",
        arrows: [{ dir: "down", from: "d2", to: "f2" }],
        description: talentText`Increases your Intellect by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%. In addition, while in Bear or Dire Bear Form your Stamina is increased by ${[
          4,
          8,
          12,
          16,
          20,
        ]}% and while in Cat Form your Strength is increased by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%.`,
      },
      "Leader of the Pack": {
        name: "Leader of the Pack",
        pos: "g2",
        icon: icons["spell_nature_unyeildingstamina"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`While in Cat, Bear or Dire Bear Form, the Leader of the Pack increases ranged and melee critical chance of all party members within 45 yards by 3%`,
      },
    },
  },
  Restoration: {
    name: "Restoration",
    background: backgrounds["restoration"],
    icon: icons["spell_nature_healingtouch"],
    talents: {
      "Improved Mark of the Wild": {
        name: "Improved Mark of the Wild",
        pos: "a2",
        icon: icons["spell_nature_regeneration"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the effects of your Mark of the Wild and Gift of the Wild spells by ${[
          7,
          14,
          21,
          28,
          35,
        ]}%.`,
      },
      Furor: {
        name: "Furor",
        pos: "a3",
        icon: icons["spell_nature_unyeildingstamina"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives you ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.`,
      },
      "Improved Healing Touch": {
        name: "Improved Healing Touch",
        pos: "b1",
        icon: icons["spell_nature_healingtouch"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the cast time of your Healing Touch spell by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec.`,
      },
      "Nature's Focus": {
        name: "Nature's Focus",
        pos: "b2",
        icon: icons["spell_nature_healingwavegreater"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          14,
          28,
          42,
          56,
          70,
        ]}% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.`,
      },
      "Improved Enrage": {
        name: "Improved Enrage",
        pos: "b3",
        icon: icons["ability_druid_enrage"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`The Enrage ability now instantly generates ${[
          5,
          10,
        ]} Rage.`,
      },
      Reflection: {
        name: "Reflection",
        pos: "c2",
        icon: icons["spell_frost_windwalkon"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Allows ${[
          5,
          10,
          15,
        ]}% of your Mana regeneration to continue while casting.`,
      },
      "Insect Swarm": {
        name: "Insect Swarm",
        pos: "c3",
        icon: icons["spell_nature_insectswarm"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`The enemy is swarmed by insects, decreasing their chance to hit by 2% and causing 66 Nature damage over 12 sec.`,
      },
      Subtlety: {
        name: "Subtlety",
        pos: "c4",
        icon: icons["ability_eyeoftheowl"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Reduces the threat generated by your Healing spells by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%.`,
      },
      "Tranquil Spirit": {
        name: "Tranquil Spirit",
        pos: "d2",
        icon: icons["spell_holy_elunesgrace"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Reduces the mana cost of your Healing Touch and Tranquility spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Improved Rejuvenation": {
        name: "Improved Rejuvenation",
        pos: "d4",
        icon: icons["spell_nature_rejuvenation"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the effect of your Rejuvenation spell by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Nature's Swiftness": {
        name: "Nature's Swiftness",
        pos: "e1",
        icon: icons["spell_nature_ravenform"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Improved Healing Touch",
        arrows: [{ dir: "down", from: "b1", to: "e1" }],
        description: talentText`When activated, your next Nature spell becomes an instant cast spell.`,
      },
      "Gift of Nature": {
        name: "Gift of Nature",
        pos: "e3",
        icon: icons["spell_nature_protectionformnature"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Insect Swarm",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`Increases the effect of all healing spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Improved Tranquility": {
        name: "Improved Tranquility",
        pos: "e4",
        icon: icons["spell_nature_tranquility"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Reduces the threat caused by Tranquility by ${[
          50,
          100,
        ]}%.`,
      },
      "Improved Regrowth": {
        name: "Improved Regrowth",
        pos: "f3",
        icon: icons["spell_nature_resistnature"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the critical effect chance of your Regrowth spell by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      Swiftmend: {
        name: "Swiftmend",
        pos: "g2",
        icon: icons["inv_relics_idolofrejuvenation"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Tranquil Spirit",
        arrows: [{ dir: "down", from: "d2", to: "g2" }],
        description: talentText`Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.`,
      },
    },
  },
};
