import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/mage"),
);
const icons = requireAll(require.context("../../assets/icons/mage"));

export const data: TalentData = {
  Arcane: {
    name: "Arcane",
    background: backgrounds["arcane"],
    icon: icons["spell_holy_magicalsentry"],
    talents: {
      "Wand Specialization": {name: "Wand Specialization", pos: "a1", icon: icons["inv_wand_01"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Arcane Focus": {name: "Arcane Focus", pos: "a2", icon: icons["spell_holy_devotion"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Elemental Precision": {name: "Elemental Precision", pos: "a3", icon: icons["spell_ice_magicdamage"], maxRank: 3, reqPoints: 0, description: talentText``, },
      "Arcane Resilience": {name: "Arcane Resilience", pos: "c1", icon: icons["spell_arcane_arcaneresilience"], maxRank: 3, reqPoints: 10, description: talentText``, },
      "Practical Defensive Magic": {name: "Practical Defensive Magic", pos: "b1", icon: icons["spell_shadow_detectlesserinvisibility"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Magic Absorption": {name: "Magic Absorption", pos: "b2", icon: icons["spell_nature_astralrecalgroup"], maxRank: 5, reqPoints: 5, description: talentText``, },
      "Master of Elements": {name: "Master of Elements", pos: "b3", icon: icons["spell_fire_masterofelements"], maxRank: 3, reqPoints: 5, prereq: "Elemental Precision", arrows: [{ dir: "down", from: "a3", to: "b3" }], description: talentText``, },
      "Arcane Subtlety": {name: "Arcane Subtlety", pos: "a4", icon: icons["spell_holy_dispelmagic"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Arcane Concentration": {name: "Arcane Concentration", pos: "c2", icon: icons["spell_shadow_manaburn"], maxRank: 5, reqPoints: 10, description: talentText``, },
      "Spell Twisting": {name: "Spell Twisting", pos: "c3", icon: icons["spell_fireresistancetotem_01"], maxRank: 1, reqPoints: 10, prereq: "Master of Elements", arrows: [{ dir: "down", from: "b3", to: "c3" }], description: talentText``, },
      "Practical Offensive Magic": {name: "Practical Offensive Magic", pos: "d1", icon: icons["arcane_magic"], maxRank: 2, reqPoints: 15, description: talentText``, },
      "Arcane Instability": {name: "Arcane Instability", pos: "d2", icon: icons["spell_shadow_teleport"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Arcane Meditation": {name: "Arcane Meditation", pos: "d3", icon: icons["spell_shadow_siphonmana"], maxRank: 3, reqPoints: 15, description: talentText``, },
      "Arcane Power": {name: "Arcane Power", pos: "e2", icon: icons["spell_nature_lightning"], maxRank: 1, reqPoints: 20, prereq: "Arcane Instability", arrows: [{ dir: "down", from: "d2", to: "e2" }], description: talentText``, },
      "Arcane Wrath": {name: "Arcane Wrath", pos: "e3", icon: icons["spell_arcane_arcanetorrent"], maxRank: 2, reqPoints: 20,  prereq: "Arcane Power", arrows: [{ dir: "right", from: "e2", to: "e3" }], description: talentText``, },
      "Arcane Mind": {name: "Arcane Mind", pos: "e4", icon: icons["spell_shadow_charm"], maxRank: 5, reqPoints: 20, prereq: "Arcane Meditation", arrows: [{ dir: "right-down", from: "d3", to: "d4"}, { dir: "right-down-down", from: "d4", to: "e4" }], description: talentText``, },
      "Time Pressure": {name: "Time Pressure", pos: "f1", icon: icons["inv_misc_pocketwatch_01"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Improved Arcane Power": {name: "Improved Arcane Power", pos: "f2", icon: icons["spell_nature_wispheal"], maxRank: 2, reqPoints: 25, prereq: "Arcane Power", arrows: [{ dir: "down", from: "e2", to: "f2"}], description: talentText``, },
      "Mind Mastery": {name: "Mind Mastery", pos: "f3", icon: icons["spell_arcane_mindmastery"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Brilliance Aura": {name: "Brilliance Aura", pos: "g2", icon: icons["spell_nature_brilliance"], maxRank: 1, reqPoints: 30, description: talentText``, },
    },
  },
  Fire: {
    name: "Fire",
    background: backgrounds["fire"],
    icon: icons["spell_fire_firebolt02"],
    talents: {
      "Fire Warding": {name: "Fire Warding", pos: "a1", icon: icons["spell_fire_firearmor"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Improved Fireball": {name: "Improved Fireball", pos: "a2", icon: icons["spell_fire_flamebolt"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Improved Fire Blast": {name: "Improved Fire Blast", pos: "a3", icon: icons["spell_fire_fireball"], maxRank: 4, reqPoints: 0, description: talentText``, },
      "Pyroblast": {name: "Pyroblast", pos: "a4", icon: icons["spell_fire_fireball02"], maxRank: 1, reqPoints: 0, prereq: "Improved Fire Blast", arrows: [{ dir: "right", from: "a3", to: "a4" }], description: talentText``, },
      "Flame Throwing": {name: "Flame Throwing", pos: "b1", icon: icons["spell_fire_flare"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Burning Soul": {name: "Burning Soul", pos: "b2", icon: icons["spell_fire_fire"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Impact": {name: "Impact", pos: "b3", icon: icons["spell_fire_meteorstorm"], maxRank: 5, reqPoints: 5, prereq: "Improved Fire Blast", arrows: [{ dir: "down", from: "a3", to: "b3"}], description: talentText``, },
      "Critical Mass": {name: "Critical Mass", pos: "c1", icon: icons["inv_summerfest_firepotion"], maxRank: 5, reqPoints: 10, description: talentText``, },
      "Blast Wave": {name: "Blast Wave", pos: "c2", icon: icons["spell_holy_excorcism_02"], maxRank: 1, reqPoints: 10, description: talentText``, },
      "Incinerate": {name: "Incinerate", pos: "c4", icon: icons["spell_fire_flameshock"], maxRank: 3, reqPoints: 10, description: talentText``, },
      "Blazing Speed": {name: "Blazing Speed", pos: "d2", icon: icons["ability_rogue_sprint"], maxRank: 2, reqPoints: 15, description: talentText``, },
      "Hot Streak": {name: "Hot Streak", pos: "d4", icon: icons["incinerate_war3"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Chain Reaction": {name: "Chain Reaction", pos: "e1", icon: icons["spell_fire_moltenblood"], maxRank: 1, reqPoints: 20, prereq: "Critical Mass", arrows: [{ dir: "down", from: "c1", to: "e1" }], description: talentText``, },
      "Overheat": {name: "Overheat", pos: "e2", icon: icons["spell_frost_fireresistancetotem"], maxRank: 3, reqPoints: 20, description: talentText``, },
      "Thermal Expansion": {name: "Thermal Expansion", pos: "e3", icon: icons["inv_elemental_primal_fire"], maxRank: 1, reqPoints: 20, prereq: "Blast Wave", arrows: [{ dir: "right-down", from: "c2", to: "c3"}, { dir: "right-down-down", from: "c3", to: "e3" }], description: talentText``, },
      "Improved Scorch": {name: "Improved Scorch", pos: "e4", icon: icons["spell_fire_soulburn"], maxRank: 3, reqPoints: 20, description: talentText``, },
      "Ignite": {name: "Ignite", pos: "f1", icon: icons["spell_fire_incinerate"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Fire Power": {name: "Fire Power", pos: "f3", icon: icons["spell_fire_immolation"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Pyromania": {name: "Pyromania", pos: "f4", icon: icons["inv_torch_lit"], maxRank: 2, reqPoints: 25, description: talentText``, },
      "Combustion": {name: "Combustion", pos: "g2", icon: icons["spell_fire_sealoffire"], maxRank: 1, reqPoints: 30, prereq: "Overheat", arrows: [{ dir: "down", from: "e2", to: "g2" }], description: talentText``, },
    },
  },
  Frost: {
    name: "Frost",
    background: backgrounds["frost"],
    icon: icons["spell_frost_frostbolt02"],
    talents: {
      "Frost Warding": {name: "Frost Warding", pos: "a1", icon: icons["spell_frost_frostward"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Improved Frostbolt": {name: "Improved Frostbolt", pos: "a2", icon: icons["spell_frost_frostbolt02"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Permafrost": {name: "Permafrost", pos: "a3", icon: icons["spell_frost_wisp"], maxRank: 3, reqPoints: 0, description: talentText``, },
      "Cryo Core": {name: "Cryo Core", pos: "b1", icon: icons["ice_shard"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Frostbite": {name: "Frostbite", pos: "b2", icon: icons["spell_frost_frostarmor"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Improved Frost Nova": {name: "Improved Frost Nova", pos: "b3", icon: icons["spell_frost_freezingbreath"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Frost Channeling": {name: "Frost Channeling", pos: "b4", icon: icons["spell_frost_stun"], maxRank: 5, reqPoints: 5, description: talentText``, },
      "Ice Block": {name: "Ice Block", pos: "c1", icon: icons["spell_frost_frost"], maxRank: 1, reqPoints: 10, prereq: "Cryo Core", arrows: [{ dir: "down", from: "b1", to: "c1" }], description: talentText``, },
      "Arctic Reach": {name: "Arctic Reach", pos: "c2", icon: icons["spell_shadow_darkritual"], maxRank: 2, reqPoints: 10, description: talentText``, },
      "Improved Blizzard": {name: "Improved Blizzard", pos: "c4", icon: icons["spell_frost_icestorm"], maxRank: 3, reqPoints: 10, description: talentText``, },
      "Ice Shards": {name: "Ice Shards", pos: "d2", icon: icons["spell_frost_iceshard"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Shatter": {name: "Shatter", pos: "d3", icon: icons["spell_frost_frostshock"], maxRank: 3, reqPoints: 15, prereq: "Improved Frost Nova", arrows: [{ dir: "down", from: "b3", to: "d3" }], description: talentText``, },
      "Improved Cone of Cold": {name: "Improved Cone of Cold", pos: "d4", icon: icons["spell_frost_glacier"], maxRank: 3, reqPoints: 15, description: talentText``, },
      "Ice Mirror": {name: "Ice Mirror", pos: "e1", icon: icons["inv_jewelcrafting_icediamond_02"], maxRank: 1, reqPoints: 20, prereq: "Ice Block", arrows: [{ dir: "down", from: "c1", to: "e1"}], description: talentText``, },
      "Cold Snap": {name: "Cold Snap", pos: "e2", icon: icons["spell_frost_wizardmark"], maxRank: 1, reqPoints: 20, description: talentText``, },
      "Icing": {name: "Icing", pos: "e3", icon: icons["ability_mage_coldasice"], maxRank: 5, reqPoints: 20, description: talentText``, },
      "Lord of the North Wind": {name: "Lord of the North Wind", pos: "f1", icon: icons["spell_frost_manarecharge"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Winter's Chill": {name: "Winter's Chill", pos: "f3", icon: icons["spell_frost_chillingblast"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Ice Barrier": {name: "Ice Barrier", pos: "g2", icon: icons["spell_ice_lament"], maxRank: 1, reqPoints: 30, prereq: "Cold Snap", arrows: [{ dir: "down", from: "e2", to: "g2" }], description: talentText``, },
      "Improved Ice Shields": {name: "Improved Ice Shields", pos: "g3", icon: icons["spell_ice_lament"], maxRank: 2, reqPoints: 30, prereq: "Ice Barrier", arrows: [{ dir: "right", from: "g2", to: "g3" }], description: talentText``, },
    },
  },
};
