import { areReqPointsMet, TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/warlock"),
);
const icons = requireAll(require.context("../../assets/icons/warlock"));

export const data: TalentData = {
  Affliction: {
    name: "Affliction",
    background: backgrounds["affliction"],
    icon: icons["spell_shadow_deathcoil"],
    talents: {
      "Improved Life Tap": {
        name: "Improved Life Tap",
        pos: "a2",
        icon: icons["spell_shadow_burningspirit"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText``,
      },
      "Jinx": {
        name: "Jinx",
        pos: "a3",
        icon: icons["spell_shadow_corseofmannoroth"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText``,
      },
      "Improved Corruption": {
        name: "Improved Corruption",
        pos: "a4",
        icon: icons["spell_shadow_abominationexplosion"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText``,
      },
      "Fel Concentration": {
        name: "Fel Concentration",
        pos: "b1",
        icon: icons["spell_shadow_fingerofdeath"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText``,
      },
      "Suppression": {
        name: "Suppression",
        pos: "b2",
        icon: icons["spell_shadow_unsummonbuilding"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText``,
      },
      "Improved Curse of Agony": {
        name: "Improved Curse of Agony",
        pos: "b3",
        icon: icons["spell_shadow_curseofsargeras"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText``,
      },
      "Improved Drain": {
        name: "Improved Drain",
        pos: "c1",
        icon: icons["drainingall"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText``,
      },
      "Prolonged Misery": {
        name: "Prolonged Misery",
        pos: "c2",
        icon: icons["spell_shadow_unstableafllictions"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText``,
      },
      "Amplify Curse": {
        name: "Amplify Curse",
        pos: "c3",
        icon: icons["spell_shadow_contagion"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Improved Curse of Agony",
        arrows: [{ dir: "down", from: "b3", to: "c3" }],
        description: talentText``,
      },
      "Improved Drain Soul": {
        name: "Improved Drain Soul",
        pos: "d1",
        icon: icons["spell_shadow_haunting"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText``,
      },
      "Nightfall": {
        name: "Nightfall",
        pos: "d2",
        icon: icons["spell_shadow_twilight"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText``,
      },
      "Herald of Woe": {
        name: "Herald of Woe",
        pos: "d3",
        icon: icons["cloak_of_flame"],
        maxRank: 3,
        reqPoints: 15,
        prereq: "Amplify Curse",
        arrows: [{ dir: "down", from: "c3", to: "d3" }],
        description: talentText``,
      },
      "Siphon Life": {
        name: "Siphon Life",
        pos: "e1",
        icon: icons["spell_shadow_requiem"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText``,
      },
      "Black Speech": {
        name: "Black Speech",
        pos: "e3",
        icon: icons["spell_shadow_soulleech"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText``,
      },
      "Death and Decay": {
        name: "Death and Decay",
        pos: "e4",
        icon: icons["spell_shadow_deathanddecay"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Improved Corruption",
        arrows: [{ dir: "down", from: "a4", to: "e4" }],
        description: talentText``,
      },
      "Shadow Mastery": {
        name: "Shadow Mastery",
        pos: "f1",
        icon: icons["spell_shadow_shadetruesight"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Siphon Life",
        arrows: [{ dir: "down", from: "e1", to: "f1" }],
        description: talentText``,
      },
      "Inevitable Doom": {
        name: "Inevitable Doom",
        pos: "f2",
        icon: icons["spell_shadow_auraofdarkness"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Nightfall",
        arrows: [{ dir: "down", from: "d2", to: "f2"}],
        description: talentText``,
      },
      "Bubonic Trail": {
        name: "Bubonic Trail",
        pos: "f3",
        icon: icons["spell_shadow_callofbone"],
        maxRank: 2,
        reqPoints: 25,
        description: talentText``,
      },
      "Defiler": {
        name: "Defiler",
        pos: "g2",
        icon: icons["inevitabledoom"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText``,
      },
    },
  },
  Demonology: {
    name: "Demonology",
    background: backgrounds["demonology"],
    icon: icons["spell_shadow_metamorphosis"],
    talents: {
      "Improved Imp": {
        name: "Improved Imp",
        pos: "a1",
        icon: icons["spell_shadow_summonimp"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText``,
      },
      "Improved Healthstone": {
        name: "Improved Healthstone",
        pos: "a2",
        icon: icons["inv_stone_04"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText``,
      },
      "Demonic Embrace": {
        name: "Demonic Embrace",
        pos: "a3",
        icon: icons["spell_shadow_metamorphosis"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText``,
      },
      "Improved Voidwalker": {
        name: "Improved Voidwalker",
        pos: "b1",
        icon: icons["spell_shadow_summonvoidwalker"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText``,
      },
      "Master Conjuror": {
        name: "Master Conjuror",
        pos: "b2",
        icon: icons["spell_shadow_soulgem"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText``,
      },
      "Unholy Power": {
        name: "Unholy Power",
        pos: "b3",
        icon: icons["spell_shadow_shadowworddominate"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText``,
      },
      "Improved Health Funnel": {
        name: "Improved Health Funnel",
        pos: "b4",
        icon: icons["spell_shadow_lifedrain"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText``,
      },
      "Improved Succubus": {
        name: "Improved Succubus",
        pos: "c1",
        icon: icons["spell_shadow_summonsuccubus"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText``,
      },
      "Fel Domination": {
        name: "Fel Domination",
        pos: "c2",
        icon: icons["spell_nature_removecurse"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText``,
      },
      "Demonic Onslaught": {
        name: "Demonic Onslaught",
        pos: "c3",
        icon: icons["inv_misc_horn_02"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText``,
      },
      "Damned Vanguard": {
        name: "Damned Vanguard",
        pos: "c4",
        icon: icons["demonic_resilience"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText``,
      },
      "Fel Intellect": {
        name: "Fel Intellect",
        pos: "d1",
        icon: icons["spell_holy_magicalsentry"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText``,
      },
      "Master Summoner": {
        name: "Master Summoner",
        pos: "d2",
        icon: icons["spell_shadow_impphaseshift"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Fel Domination",
        arrows: [{ dir: "down", from: "c2", to: "d2" }],
        description: talentText``,
      },
      "Fel Stamina": {
        name: "Fel Stamina",
        pos: "d4",
        icon: icons["spell_shadow_antishadow"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText``,
      },
      "Improved Felhunter": {
        name: "Improved Felhunter",
        pos: "e1",
        icon: icons["spell_shadow_summonfelhunter"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText``,
      },
      "Soul Link": {
        name: "Soul Link",
        pos: "e2",
        icon: icons["spell_shadow_gathershadows"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText``,
      },
      "Improved Enslave Demon": {
        name: "Improved Enslave Demon",
        pos: "e4",
        icon: icons["spell_shadow_enslavedemon"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText``,
      },
      "Master Demonologist": {
        name: "Master Demonilogist",
        pos: "f1",
        icon: icons["spell_shadow_shadowpact"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText``,
      },
      "Fel Pact": {
        name: "Fel Pact",
        pos: "f3",
        icon: icons["inv_helmet_08"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Demonic Onslaught",
        arrows: [{ dir: "down", from: "c3", to: "f3" }],
        description: talentText``,
      },
      "Demonic Sacrifice": {
        name: "Demonic Sacrifice",
        pos: "g2",
        icon: icons["spell_shadow_psychicscream"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Soul Link",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText``,
      },
    },
  },
  Destruction: {
    name: "Destruction",
    background: backgrounds["destruction"],
    icon: icons["spell_shadow_rainoffire"],
    talents: {
      "Destructive Reach": {
        name: "Destructive Reach", 
        pos: "a1", 
        icon: icons["spell_shadow_corpseexplode"], 
        maxRank: 2, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Bane": {
        name: "Bane", 
        pos: "a2", 
        icon: icons["spell_shadow_deathpact"], 
        maxRank: 5, 
        reqPoints: 0, description: talentText``, 
      },
      "Aftermath": {
        name: "Aftermath", 
        pos: "a3", 
        icon: icons["spell_fire_fire"], 
        maxRank: 3, 
        reqPoints: 0, description: talentText``, 
      },
      "Cataclysm": {
        name: "Cataclysm", 
        pos: "b1", 
        icon: icons["spell_fire_windsofwoe"], 
        maxRank: 3, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Devastation": {
        name: "Devastation", 
        pos: "b2", 
        icon: icons["spell_fire_flameshock"], 
        maxRank: 5, 
        reqPoints: 5, description: talentText``, 
      },
      "Demonic Power": {
        name: "Demonic Power", 
        pos: "b3", 
        icon: icons["spell_fire_firebolt"], 
        maxRank: 2, 
        reqPoints: 5, description: talentText``, 
      },
      "Intensity": {
        name: "Intensity", 
        pos: "c1", 
        icon: icons["spell_fire_lavaspawn"], 
        maxRank: 2, 
        reqPoints: 10, description: talentText``, 
      },
      "Ruin": {
        name: "Ruin", 
        pos: "c2", 
        icon: icons["spell_shadow_shadowwordpain"], 
        maxRank: 5, 
        reqPoints: 10, 
        prereq: "Devastation", 
        arrows: [{dir: "down", from: "b2", to: "c2" }],
        description: talentText``,
      },
      "Feeding Demons": {
        name: "Feeding Demons", 
        pos: "c3", 
        icon: icons["dragon_devour"], 
        maxRank: 2, 
        reqPoints: 10, 
        prereq: "Demonic Power", 
        arrows: [{ dir: "down", from: "b3", to: "c3" }], 
        description: talentText``, 
      },
      "Shadowburn": {
        name: "Shadowburn", 
        pos: "c4", 
        icon: icons["spell_shadow_scourgebuild"], 
        maxRank: 1, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Improved Immolate": {
        name: "Improved Immolate", 
        pos: "d2", 
        icon: icons["spell_fire_immolation"], 
        maxRank: 3, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Bring the Pain": {
        name: "Bring the Pain", 
        pos: "d3", 
        icon: icons["spell_fire_soulburn"], 
        maxRank: 2, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Improved Shadow Bolt": {
        name: "Improved Shadow Bolt", 
        pos: "d4", 
        icon: icons["spell_shadow_shadowbolt"], 
        maxRank: 5, 
        reqPoints: 15,
        description: talentText``, 
      },
      "Pyroclasm": {
        name: "Pyroclasm", 
        pos: "e1", 
        icon: icons["spell_fire_volcano"], 
        maxRank: 2, 
        reqPoints: 20, 
        prereq: "Intensity", 
        arrows: [{ dir: "down", from: "c1", to: "e1"}], 
        description: talentText``, 
      },
      "Conflagrate": {
        name: "Conflagrate", 
        pos: "e2", 
        icon: icons["spell_fire_fireball"], 
        maxRank: 1, 
        reqPoints: 20, 
        prereq: "Improved Immolate", 
        arrows: [{ dir: "down", from: "d2", to: "e2" }], 
        description: talentText``, 
      },
      "Sadism": {
        name: "Sadism", 
        pos: "e3", 
        icon: icons["spell_shadow_unstableaffliction_3"], 
        maxRank: 5, 
        reqPoints: 20, 
        prereq: "Bring the Pain", 
        arrows: [{ dir: "down", from: "d3", to: "e3" }], 
        description: talentText``, 
      },
      "Mayhem": {
        name: "Mayhem", 
        pos: "e4", 
        icon: icons["spell_holy_excorcism_02"], 
        maxRank: 1, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Shadowstorm ": {
        name: "Shadowstorm ", 
        pos: "f2", 
        icon: icons["spell_shadow_chilltouch"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Emberstorm": {
        name: "Emberstorm", 
        pos: "f3", 
        icon: icons["spell_fire_selfdestruct"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Shock and Awe": {
        name: "Shock and Awe", 
        pos: "g2", 
        icon: icons["phoenix"], 
        maxRank: 1, 
        reqPoints: 30, 
        description: talentText``, 
      },
    },
  },
};
