import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/shaman"),
);
const icons = requireAll(require.context("../../assets/icons/shaman"));

export const data: TalentData = {
  Elemental: {
    name: "Elemental",
    background: backgrounds["elemental"],
    icon: icons["spell_nature_lightning"],
    talents: {
      "Storm Reach": {
        name: "Storm Reach", 
        pos: "a1", 
        icon: icons["spell_nature_stormreach"], 
        maxRank: 2, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Convection": {
        name: "Convection", 
        pos: "b2", 
        icon: icons["spell_nature_wispsplode"], 
        maxRank: 3, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Concussion": {
        name: "Concussion", 
        pos: "a3", 
        icon: icons["spell_fire_fireball"], 
        maxRank: 5, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Earth's Grasp": {
        name: "Earth's Grasp", 
        pos: "b1", 
        icon: icons["spell_nature_stoneclawtotem"], 
        maxRank: 2, reqPoints: 5, 
        description: talentText``, 
      },
      "Elemental Warding": {
        name: "Elemental Warding", 
        pos: "a2", 
        icon: icons["spell_nature_spiritarmor"], 
        maxRank: 3, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Call of Flame": {
        name: "Call of Flame", 
        pos: "b3", 
        icon: icons["spell_fire_immolation"], 
        maxRank: 3, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Reverberation": {
        name: "Reverberation", 
        pos: "b4", 
        icon: icons["spell_frost_frostward"], 
        maxRank: 5, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Sand Blast": {
        name: "Sand Blast", pos: "c1", 
        icon: icons["spell_fire_windsofwoe"], 
        maxRank: 1, 
        reqPoints: 10, 
        prereq: "Earth's Grasp", 
        arrows: [{ dir: "down", from: "b1", to: "c1" }], 
        description: talentText``, 
      },
      "Elemental Focus": {
        name: "Elemental Focus", pos: "c2", 
        icon: icons["spell_shadow_manaburn"], 
        maxRank: 5, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Call of Thunder": {
        name: "Call of Thunder",
         pos: "c3", 
        icon: icons["spell_nature_callstorm"], 
        maxRank: 2, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Eye of the Storm": {

        name: "Eye of the Storm", 
        pos: "c4", 
        icon: icons["spell_nature_eyeofthestorm"], 
        maxRank: 3, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Elemental Fury": {
        name: "Elemental Fury", 
        pos: "d2", 
        icon: icons["spell_fire_volcano"], 
        maxRank: 5, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Elemental Devastation": {

        name: "Elemental Devastation", 
        pos: "d4", 
        icon: icons["spell_fire_elementaldevastation"], 
        maxRank: 3, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Improved Fire Totems": {
        name: "Improved Fire Totems", 
        pos: "e1", 
        icon: icons["spell_fire_sealoffire"], 
        maxRank: 2, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Elemental Mastery": {
        name: "Elemental Mastery", 
        pos: "e2", 
        icon: icons["spell_nature_wispheal"], 
        maxRank: 1, 
        reqPoints: 20, 
        prereq: "Elemental Fury", 
        arrows: [{ dir: "down", from: "d2", to: "e2" }], 
        description: talentText``, 
      },
      "Lightning Mastery": {
        name: "Lightning Mastery", 
        pos: "e3", 
        icon: icons["spell_lightning_lightningbolt01"], 
        maxRank: 5, 
        reqPoints: 20, 
        prereq: "Call of Thunder", 
        arrows: [{ dir: "down", from: "c3", to: "e3" }], 
        description: talentText``, 
      },
      "Elemental Precision": {
        name: "Elemental Precision", 
        pos: "f1", 
        icon: icons["spell_nature_elementalprecision_1"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Lightning Overlord": {
        name: "Lightning Overlord", 
        pos: "f3", 
        icon: icons["inv_helmet_06"], 
        maxRank: 2, 
        reqPoints: 25, 
        prereq: "Lightning Mastery", 
        arrows: [{ dir: "down", from: "e3", to: "f3" }], 
        description: talentText``, 
      },
      "Static Field": {
        name: "Static Field", 
        pos: "f4", 
        icon: icons["spell_shaman_staticshock"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Earthquake": {
        name: "Earthquake", 
        pos: "g2", 
        icon: icons["spell_nature_earthquake"], 
        maxRank: 1, 
        reqPoints: 30, 
        prereq: "Elemental Mastery", 
        arrows: [{ dir: "down", from: "e2", to: "g2" }], 
        description: talentText``, 
      },
    },
  },
  Enhancement: {
    name: "Enhancement",
    background: backgrounds["enhancement"],
    icon: icons["spell_nature_lightningshield"],
    talents: {
      "Elemental Weapons": {
        name: "Elemental Weapons", 
        pos: "a1", 
        icon: icons["spell_fire_flametounge"], 
        maxRank: 3, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Ancestral Knowledge": {
        name: "Ancestral Knowledge", 
        pos: "a2", icon: icons["spell_shadow_grimward"], 
        maxRank: 5, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Shield Specialization": {
        name: "Shield Specialization", 
        pos: "a3", 
        icon: icons["inv_shield_06"], 
        maxRank: 2, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Guardian Totems": {
        name: "Guardian Totems", 
        pos: "b1", 
        icon: icons["spell_nature_stoneskintotem"], 
        maxRank: 2, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Thundering Strikes": {
        name: "Thundering Strikes", 
        pos: "b2", 
        icon: icons["ability_thunderbolt"], 
        maxRank: 5, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Toughness": {
        name: "Toughness", 
        pos: "b4", 
        icon: icons["spell_holy_devotion"], 
        maxRank: 3, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Rockhide": {
        name: "Rockhide", 
        pos: "c1", 
        icon: icons["stoneskinz"], 
        maxRank: 5, 
        reqPoints: 10, 
        prereq: "Guardian Totems", 
        arrows: [{ dir: "down", from: "b1", to: "c1" }], 
        description: talentText``, 
      },
      "Flurry": {
        name: "Flurry", 
        pos: "c2", 
        icon: icons["ability_ghoulfrenzy"], 
        maxRank: 5, 
        reqPoints: 10, 
        prereq: "Thundering Strikes", 
        arrows: [{ dir: "down", from: "b2", to: "c2" }], 
        description: talentText``, 
      },
      "Rocky Bash": {
        name: "Rocky Bash", 
        pos: "c3", 
        icon: icons["inv_stone_08"], 
        maxRank: 1, 
        reqPoints: 10, 
        prereq: "Shield Specialization", 
        arrows: [{ dir: "down", from: "a3", to: "c3" }], 
        description: talentText``, 
      },
      "Weapon Mastery": {
        name: "Weapon Mastery", 
        pos: "c4", 
        icon: icons["ability_hunter_swiftstrike"], 
        maxRank: 5, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Improved Weapon Totems": {
        name: "Improved Weapon Totems", 
        pos: "d1", 
        icon: icons["spell_fire_enchantweapon"], 
        maxRank: 2, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Primal Endurance": {
        name: "Primal Endurance", 
        pos: "d2", 
        icon: icons["spell_nature_ancestralguardian"], 
        maxRank: 5, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Improved Ghost Wolf": {
        name: "Improved Ghost Wolf", 
        pos: "d3", 
        icon: icons["spell_nature_spiritwolf"], 
        maxRank: 2, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Improved Lightning Shield": {
        name: "Improved Lightning Shield", 
        pos: "d4", 
        icon: icons["spell_nature_lightningshield"], 
        maxRank: 3, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Enhancing Totems": {
        name: "Enhancing Totems", 
        pos: "e1", 
        icon: icons["spell_nature_earthbindtotem"], 
        maxRank: 2, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Bloodlust": {
        name: "Bloodlust", 
        pos: "e2", 
        icon: icons["spell_nature_bloodlust"], 
        maxRank: 1, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Anticipation": {
        name: "Anticipation", 
        pos: "e3", 
        icon: icons["spell_nature_mirrorimage"], 
        maxRank: 3, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Armaments of Storm": {
        name: "Armaments of Storm", 
        pos: "f1", 
        icon: icons["spell_nature_stormhammer"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Shamanism": {
        name: "Shamanism", 
        pos: "f3", 
        icon: icons["spell_nature_shamanism"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, 
      },
      "Aftershock": {
        name: "Aftershock", 
        pos: "g2", 
        icon: icons["spell_nature_elementalprecision_2"], 
        maxRank: 1, 
        reqPoints: 30, 
        prereq: "Bloodlust", 
        arrows: [{ dir: "down", from: "e2", to: "g2" }], 
        description: talentText``, 
      },
    },
  },
  Restoration: {
    name: "Restoration",
    background: backgrounds["restoration"],
    icon: icons["spell_nature_magicimmunity"],
    talents: {
      "Nature's Guidance": {
        name: "Nature's Guidance", 
        pos: "a1", 
        icon: icons["spell_frost_stun"], 
        maxRank: 3, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Tidal Mastery": {
        name: "Tidal Mastery", 
        pos: "a2", 
        icon: icons["spell_nature_tranquility"], 
        maxRank: 5, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Totemic Mastery": {
        name: "Totemic Mastery", 
        pos: "a3", 
        icon: icons["spell_nature_nullward"], 
        maxRank: 2, 
        reqPoints: 0, 
        description: talentText``, 
      },
      "Improved Healing Wave": {
        name: "Improved Healing Wave", 
        pos: "b1", 
        icon: icons["spell_nature_magicimmunity"], 
        maxRank: 5, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Totemic Focus": {
        name: "Totemic Focus", 
        pos: "b3", 
        icon: icons["spell_nature_moonglow"], 
        maxRank: 2, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Nature Grace": {
        name: "Nature Grace", 
        pos: "b4", 
        icon: icons["spell_nature_healingtouch"], 
        maxRank: 3, 
        reqPoints: 5, 
        description: talentText``, 
      },
      "Nature's Guardian": {
        name: "Nature's Guardian", 
        pos: "c1", 
        icon: icons["spell_nature_natureguardian"], 
        maxRank: 3, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Tidal Shield": {
        name: "Tidal Shield", 
        pos: "c2", 
        icon: icons["spell_frost_wisp"], 
        maxRank: 1, 
        reqPoints: 10, 
        prereq: "Tidal Mastery", 
        arrows: [{ dir: "down", from: "a2", to: "c2" }], 
        description: talentText``, 
      },
      "Spiritwalking": {
        name: "Spiritwalking", 
        pos: "c3", 
        icon: icons["spiritwalker"], 
        maxRank: 2, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Nature Focus": {
        name: "Nature Focus", 
        pos: "c4", 
        icon: icons["spell_nature_healingwavelesser"], 
        maxRank: 5, 
        reqPoints: 10, 
        description: talentText``, 
      },
      "Nature Spirit": {
        name: "Nature Spirit", 
        pos: "d1", 
        icon: icons["spell_nature_preservation"], 
        maxRank: 5, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Tidal Focus": {
        name: "Tidal Focus", 
        pos: "d2", 
        icon: icons["spell_frost_manarecharge"], 
        maxRank: 5, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Restorative Totems": {
        name: "Restorative Totems", 
        pos: "d3", 
        icon: icons["spell_nature_manaregentotem"], 
        maxRank: 2, 
        reqPoints: 15, 
        description: talentText``, 
      },
      "Ancestral Healing": {
        name: "Ancestral Healing", 
        pos: "e1", 
        icon: icons["spell_nature_undyingstrength"], 
        maxRank: 3, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Purification": {
        name: "Purification", 
        pos: "e2", 
        icon: icons["spell_frost_wizardmark"], 
        maxRank: 5, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Nature's Swiftness": {
        name: "Nature's Swiftness", 
        pos: "e3", 
        icon: icons["spell_nature_ravenform"], 
        maxRank: 1, 
        reqPoints: 20, 
        description: talentText``, 
      },
      "Focused Mind": {
        name: "Focused Mind", 
        pos: "e4", 
        icon: icons["spell_nature_focusedmind"], 
        maxRank: 3, 
        reqPoints: 20, 
        prereq: "Nature Focus", 
        arrows: [{ dir: "down", from: "c4", to: "e4" }], 
        description: talentText``, 
      },
      "Healing Way": {
        name: "Healing Way", 
        pos: "f1", 
        icon: icons["spell_nature_healingway"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, },
      "Meditation": {
        name: "Meditation", 
        pos: "f3", 
        icon: icons["spell_nature_sleep"], 
        maxRank: 5, 
        reqPoints: 25, 
        description: talentText``, },
      "Cleansing Wave": {
        name: "Cleansing Wave", 
        pos: "g2", 
        icon: icons["spell_shadow_demonbreath"], 
        maxRank: 1, 
        reqPoints: 30, 
        prereq: "Purification", 
        arrows: [{ dir: "down", from: "e2", to: "g2" }], 
        description: talentText``, 
      },
    },
  },
};
