import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/rogue"),
);
const icons = requireAll(require.context("../../assets/icons/rogue"));

export const data: TalentData = {
  Assassination: {
    name: "Assassination",
    background: backgrounds["assassination"],
    icon: icons["ability_rogue_eviscerate"],
    talents: {
      "Improved Eviscerate": {name: "Improved Eviscerate", pos: "a1", icon: icons["ability_rogue_eviscerate"], maxRank: 3, reqPoints: 0, description: talentText``, },
      "Remorseless Attacks": {name: "Remorseless Attacks", pos: "a2", icon: icons["ability_fiegndead"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Malice": {name: "Malice", pos: "a3", icon: icons["ability_racial_bloodrage"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Ruthlessness": {name: "Ruthlessness", pos: "b1", icon: icons["ability_druid_disembowel"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Seek and Destroy": {name: "Seek and Destroy", pos: "b2", icon: icons["ability_rogue_bloodyeye"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Exhaustion": {name: "Exhaustion", pos: "b4", icon: icons["spell_shadow_curseofsargeras"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Relentless Strikes": {name: "Relentless Strikes", pos: "c1", icon: icons["ability_warrior_decisivestrike"], maxRank: 1, reqPoints: 10, description: talentText``, },
      "Lethality": {name: "Lethality", pos: "c3", icon: icons["ability_criticalstrike"], maxRank: 5, reqPoints: 10, prereq: "Malice", arrows: [{ dir: "down", from: "a3", to: "c3" }], description: talentText``, },
      "Improved Poisons": {name: "Improved Poisons", pos: "c4", icon: icons["ability_poisons"], maxRank: 5, reqPoints: 10, description: talentText``, },
      "Vile Poisons": {name: "Vile Poisons", pos: "d1", icon: icons["ability_rogue_feigndeath"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Death Mark": {name: "Death Mark", pos: "d2", icon: icons["spell_shadow_deathscream"], maxRank: 2, reqPoints: 15, prereq: "Seek and Destroy", arrows: [{ dir: "down", from: "b2", to: "d2" }], description: talentText``, },
      "Bloodthirsty": {name: "Bloodthirsty", pos: "d3", icon: icons["ability_warrior_bloodfrenzy"], maxRank: 3, reqPoints: 15, description: talentText``, },
      "Vitality": {name: "Vitality", pos: "d4", icon: icons["ability_rogue_quickrecovery"], maxRank: 2, reqPoints: 15, description: talentText``, },
      "Cold Blood": {name: "Cold Blood", pos: "e2", icon: icons["spell_ice_lament"], maxRank: 1, reqPoints: 20, description: talentText``, },
      "Improved Kidney Shot": {name: "Improved Kidney Shot", pos: "e3", icon: icons["ability_rogue_kidneyshot"], maxRank: 3, reqPoints: 20, description: talentText``, },
      "Total Control": {name: "Total Control", pos: "e4", icon: icons["spell_shadow_deathpact"], maxRank: 2, reqPoints: 20, prereq: "Improved Kidney Shot", arrows: [{ dir: "right", from: "e3", to: "e4" }], description: talentText``, },
      "Seal Fate": {name: "Seal Fate", pos: "f1", icon: icons["spell_shadow_chilltouch"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Cold Blooded": {name: "Cold Blooded", pos: "f2", icon: icons["spell_ice_lament"], maxRank: 2, reqPoints: 25, prereq: "Cold Blood", arrows: [{ dir: "down", from: "e2", to: "f2" }], description: talentText``, },
      "Gaining an Advantage": {name: "Gaining an Advantage", pos: "f3", icon: icons["banish_2"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Vigor": {name: "Vigor", pos: "g2", icon: icons["spell_nature_earthbindtotem"], maxRank: 1, reqPoints: 30, description: talentText``, },
    },
  },
  Combat: {
    name: "Combat",
    background: backgrounds["combat"],
    icon: icons["ability_backstab"],
    talents: {
      "Improved Gouge": {name: "Improved Gouge", pos: "a1", icon: icons["ability_gouge"], maxRank: 3, reqPoints: 0, description: talentText``, },
      "Improved Sinister Strike": {name: "Improved Sinister Strike", pos: "a2", icon: icons["spell_shadow_ritualofsacrifice"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Bitter Experience": {name: "Bitter Experience", pos: "a3", icon: icons["inv_helmet_46"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Improved Backstab": {name: "Improved Backstab", pos: "b1", icon: icons["ability_backstab"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Deflection": {name: "Deflection", pos: "b2", icon: icons["ability_parry"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Precision": {name: "Precision", pos: "b3", icon: icons["ability_marksmanship"], maxRank: 5, reqPoints: 5, description: talentText``, },
      "Improved Sprint": {name: "Improved Sprint", pos: "b4", icon: icons["ability_rogue_sprint"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Improved Kick": {name: "Improved Kick", pos: "c1", icon: icons["ability_kick"], maxRank: 2, reqPoints: 10, description: talentText``, },
      "Riposte": {name: "Riposte", pos: "c2", icon: icons["ability_warrior_challange"], maxRank: 1, reqPoints: 10, prereq: "Deflection", arrows: [{ dir: "down", from: "b2", to: "c2" }], description: talentText``, },
      "Dual Wield Specialization": {name: "Dual Wield Specialization", pos: "c3", icon: icons["ability_dualwield"], maxRank: 5, reqPoints: 10, prereq: "Precision", arrows: [{ dir: "down", from: "b3", to: "c3" }], description: talentText``, },
      "Close Quarters Combat": {name: "Close Quarters Combat", pos: "c4", icon: icons["inv_weapon_shortblade_05"], maxRank: 5, reqPoints: 10, description: talentText``, },
      "Physical Prowess": {name: "Physical Prowess", pos: "d1", icon: icons["spell_nature_strength"], maxRank: 2, reqPoints: 15, description: talentText``, },
      "Mace Specialization": {name: "Mace Specialization", pos: "d2", icon: icons["inv_mace_01"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Sword Specialization": {name: "Sword Specialization", pos: "d3", icon: icons["inv_sword_27"], maxRank: 5, reqPoints: 15, description: talentText``, },
      "Blade Flurry": {name: "Blade Flurry", pos: "e2", icon: icons["ability_warrior_punishingblow"], maxRank: 1, reqPoints: 20, description: talentText``, },
      "Steadfast Determination": {name: "Steadfast Determination", pos: "e3", icon: icons["spell_nature_focusedmind"], maxRank: 5, reqPoints: 20, description: talentText``, },
      "Battle Rush": {name: "Battle Rush", pos: "f1", icon: icons["ability_warrior_rampage"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Weapon Expertise": {name: "Weapon Expertise", pos: "f2", icon: icons["spell_holy_blessingofstrength"], maxRank: 2, reqPoints: 25, prereq: "Blade Flurry", arrows: [{ dir: "down", from: "e2", to: "f2" }], description: talentText``, },
      "Aggression": {name: "Aggression", pos: "f3", icon: icons["ability_racial_avatar"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Adrenaline Rush": {name: "Adrenaline Rush", pos: "g2", icon: icons["spell_shadow_shadowworddominate"], maxRank: 1, reqPoints: 30, description: talentText``, },
    },
  },
  Subtlety: {
    name: "Subtlety",
    background: backgrounds["subtlety"],
    icon: icons["ability_stealth"],
    talents: {
      "Improved Sap": {name: "Improved Sap", pos: "a1", icon: icons["ability_sap"], maxRank: 3, reqPoints: 0, description: talentText``, },
      "Master of Deception": {name: "Master of Deception", pos: "a2", icon: icons["spell_shadow_charm"], maxRank: 2, reqPoints: 0, description: talentText``, },
      "Opportunity": {name: "Opportunity", pos: "a3", icon: icons["ability_warrior_warcry"], maxRank: 5, reqPoints: 0, description: talentText``, },
      "Initiative": {name: "Initiative", pos: "b1", icon: icons["spell_shadow_fumble"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Sleight of Hand": {name: "Sleight of Hand", pos: "b2", icon: icons["ability_rogue_feint"], maxRank: 3, reqPoints: 5, description: talentText``, },
      "Thug Life": {name: "Thug Life", pos: "b4", icon: icons["inv_misc_bandana_03"], maxRank: 2, reqPoints: 5, description: talentText``, },
      "Setup": {name: "Setup", pos: "c1", icon: icons["spell_nature_mirrorimage"], maxRank: 3, reqPoints: 10, description: talentText``, },
      "Ghostly Strike": {name: "Ghostly Strike", pos: "c2", icon: icons["spell_shadow_curse"], maxRank: 1, reqPoints: 10, description: talentText``, },
      "Improved Ambush": {name: "Improved Ambush", pos: "c3", icon: icons["ability_rogue_ambush"], maxRank: 3, reqPoints: 10, prereq: "Opportunity", arrows: [{ dir: "down", from: "a3", to: "c3" }], description: talentText``, },
      "Camouflage": {name: "Camouflage", pos: "c4", icon: icons["ability_stealth"], maxRank: 5, reqPoints: 10, description: talentText``, },
      "Heightened Senses": {name: "Heightened Senses", pos: "d1", icon: icons["ability_ambush"], maxRank: 2, reqPoints: 15, description: talentText``, },
      "Elusiveness": {name: "Elusiveness", pos: "d2", icon: icons["spell_magic_lesserinvisibilty"], maxRank: 2, reqPoints: 15, prereq: "Ghostly Strike", arrows: [{ dir: "down", from: "c2", to: "d2" }], description: talentText``, },
      "Serrated Blades": {name: "Serrated Blades", pos: "d3", icon: icons["inv_sword_17"], maxRank: 3, reqPoints: 15, description: talentText``, },
      "Cloak of Shadows": {name: "Cloak of Shadows", pos: "e2", icon: icons["spell_shadow_nethercloak"], maxRank: 1, reqPoints: 20, description: talentText``, },
      "Dirty Deeds": {name: "Dirty Deeds", pos: "e3", icon: icons["spell_shadow_summonsuccubus"], maxRank: 3, reqPoints: 20, description: talentText``, },
      "Hemorrhage": {name: "Hemorrhage", pos: "e4", icon: icons["spell_shadow_lifedrain"], maxRank: 1, reqPoints: 20, prereq: "Serrated Blades", arrows: [{ dir: "right-down", from: "d3", to: "d4" }, { dir: "right-down-down", from: "d4", to: "e4" }], description: talentText``, },
      "Brigandage": {name: "Brigandage", pos: "f1", icon: icons["inv_sword_11"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Deadliness": {name: "Deadliness", pos: "f3", icon: icons["inv_weapon_crossbow_11"], maxRank: 5, reqPoints: 25, description: talentText``, },
      "Enveloping Shadows": {name: "Enveloping Shadows", pos: "g2", icon: icons["ability_rogue_envelopingshadows"], maxRank: 3, reqPoints: 30, prereq: "Cloak of Shadows", arrows: [{ dir: "down", from: "e2", to: "g2" }], description: talentText``, },
      "Preparation": {name: "Preparation", pos: "g3", icon: icons["spell_shadow_antishadow"], maxRank: 1, reqPoints: 30, description: talentText``, },
    },
  },
};
